menu:
  Home:
  Archives: archives

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username: adamhathcock
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: false

fancybox: false
